import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { ProposalModal } from "@/components/proposal-modal";
import { ProposalWizard } from "@/components/proposal-wizard";
import { Card, EmptyState, PageHeader, Td, Th, formatDate } from "@/components/ui";
import { getLeads, getProposals } from "@/lib/queries";

export const dynamic = "force-dynamic";

export default async function ProposalsPage() {
  const [rows, leads] = await Promise.all([getProposals(), getLeads()]);
  const eligibleLeads = leads
    .filter((l) => l.status !== "archived")
    .map((l) => ({ id: l.id, business_name: l.business_name }));

  return (
    <AppShell>
      <section className="p-6">
        <PageHeader
          title="Proposals"
          subtitle="Tailored proposals generated by the Proposal agent."
          actions={<ProposalWizard leads={eligibleLeads} />}
        />

        <Card className="overflow-hidden">
          {rows.length === 0 ? (
            <EmptyState title="No proposals yet" hint='Click "New proposal" above to generate one.' />
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="border-b border-border-c">
                  <tr>
                    <Th>Business</Th>
                    <Th>Services</Th>
                    <Th>Budget</Th>
                    <Th>Preview</Th>
                    <Th>Created</Th>
                    <Th></Th>
                  </tr>
                </thead>
                <tbody>
                  {rows.map((row) => (
                    <tr key={row.id} className="border-b border-border-c/50 last:border-0 hover:bg-surface-2/50">
                      <Td className="font-medium">
                        <Link href={`/leads/${row.lead_id}`} className="text-brand hover:underline">
                          {row.business_name}
                        </Link>
                      </Td>
                      <Td className="capitalize">{row.services?.join(", ") ?? "—"}</Td>
                      <Td className="capitalize">{row.budget_range ?? "—"}</Td>
                      <Td className="text-ink-secondary max-w-md truncate">{row.content ?? "—"}</Td>
                      <Td className="text-ink-muted">{formatDate(row.created_at)}</Td>
                      <Td><ProposalModal row={row} /></Td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </Card>
      </section>
    </AppShell>
  );
}
